//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazZiya.Localization.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelBindingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelBindingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LazZiya.Localization.ResourceFiles.ModelBindingResource", typeof(ModelBindingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for &apos;{1}&apos;.
        /// </summary>
        public static string AttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("AttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for the &apos;{0}&apos; property was not provided.
        /// </summary>
        public static string MissingBindRequiredValueAccessor {
            get {
                return ResourceManager.GetString("MissingBindRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required.
        /// </summary>
        public static string MissingKeyOrValueAccessor {
            get {
                return ResourceManager.GetString("MissingKeyOrValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty request body is required.
        /// </summary>
        public static string MissingRequestBodyRequiredValueAccessor {
            get {
                return ResourceManager.GetString("MissingRequestBodyRequiredValueAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid.
        /// </summary>
        public static string NonPropertyAttemptedValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyAttemptedValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid.
        /// </summary>
        public static string NonPropertyUnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("NonPropertyUnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number.
        /// </summary>
        public static string NonPropertyValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("NonPropertyValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid for &apos;{0}&apos;.
        /// </summary>
        public static string UnknownValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("UnknownValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid.
        /// </summary>
        public static string ValueIsInvalidAccessor {
            get {
                return ResourceManager.GetString("ValueIsInvalidAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be a number.
        /// </summary>
        public static string ValueMustBeANumberAccessor {
            get {
                return ResourceManager.GetString("ValueMustBeANumberAccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must not be null.
        /// </summary>
        public static string ValueMustNotBeNullAccessor {
            get {
                return ResourceManager.GetString("ValueMustNotBeNullAccessor", resourceCulture);
            }
        }
    }
}
